### Send message
POST https://shebogholo.com/springboot2/chat/api/v1/chat/send
Content-Type: application/json

{
  "message": "thank you",
  "messageTo": "shebo"
}

### Register new user
POST https://shebogholo.com/springboot2/chat/api/v1/chat/register
Content-Type: application/json

{
  "username": "ally",
  "password": "ally"
}

### Logout
GET https://shebogholo.com/springboot2/chat/api/v1/chat/logout